### ISSUE TITLE
ValueError: list.remove(x): x not in list in process_mols.py  line 692, in get_geometry_graph

### ISSUE THREAD

**Issue by moritzschaefer** [HannesStark/EquiBind#21]
I get the following error for a specific ligand-protein pair:

```
Trying to load ligand_106.sdf
Docking the receptor protein_A.pdb
To the ligand ligand_106.sdf
Traceback (most recent call last):
  File "inference.py", line 473, in <module>
    inference_from_files(args)
  File "inference.py", line 350, in inference_from_files
    geometry_graph = get_geometry_graph(lig)
  File "/home/moritz/Projects/EquiBind/commons/process_mols.py", line 692, in get_geometry_graph
    all_dst_idx.remove(src_idx)
ValueError: list.remove(x): x not in list
```

(I followed the instruction in the README and ran `python inference.py --config=configs_clean/inference.yml`)

**Comment by HannesStark** [comment]
Hi,
Thanks for mentioning the problem!
Would you mind sending me the specific ligand-protein pair? hstark@mit.edu

**Comment by HannesStark** [comment]
Thanks for sending it over - I fixed the issue and it should work now after pulling the most recent commit!

The problem was that this version of the graph creation for the geometry regularization did not work with ligand atoms that do not have any neighbors in the sense of not having any bonds that connect them to another atom.
This is now supported, however, the model was never trained with ligand files that have a completely disconnected atom. Likely the predictions are better if the "lone atom" is removed.

I hope that helps!
