### ISSUE TITLE
Memory requirements for training?

### ISSUE THREAD

**Issue by neild0** [HannesStark/EquiBind#29]
I've been trying to train the model using the `RDKitCoords_flexible_self_docking.yml` configuration, and after modifying the code based on #6, I am having a RAM overflow problem. 

It seems like the code loads receptors into memory — just wondering if this is supposed it happen and take so much memory, and, if so, how much is recommended to run this project. Thanks!

**Comment by HannesStark** [comment]
I am not sure how much RAM exactly is needed to perform the preprocessing of the data. If you do not have sufficient RAM you can modify the code to preprocess the data in portions instead of doing everything at once.
In pdbbind.py you find the preprocess function which currently loads all complexes into memory at the same time. You could instead do this for only e.g. 500 complexes at a time.
