### ISSUE TITLE
Hydrogens on receptors

### ISSUE THREAD

**Issue by amfaber** [HannesStark/EquiBind#33]
Hi Hannes, thanks for the amazing tool :) In the paper, you note that you add hydrogens to the receptors using reduce. However, my understanding is that EquiBind uses a graph of the residues to represent the protein. What is the purpose of adding hydrogens to the receptor, and (more importantly), should I be doing the same when running inference? Thanks again

On an unrelated note, I saw a [request for support for multi-ligand files](https://github.com/HannesStark/EquiBind/issues/11). I've created my own implementation for that exact purpose, which is able to handle large sdf and smiles files lazily, running inference as the file is processed and writing the results along the way without needing to load the entire file at once. Would you be interested in a pull request?

**Comment by HannesStark** [comment]
Hi!
We ran reduce and include hydrogens since we also have experiments with the sidechains, including all atoms, and using surface atoms.
I am not 100% certain that reduce does not also do some changes to the backbone.
Additionally, reduce runs some corrections that sometimes flip a HIS side chain in my understanding. With the model including information about the direction of a side chain, I think it is safest to also run reduce on the receptors.

The pull request with support for multi-ligand files would be highly appreciated!
Thank you very much if you test that everything else still works and make that pull request!

**Comment by amfaber** [comment]
Thank you for the swift response! If it is in general recommended to run one's proteins through reduce before doing inference, may I suggest adding it to the main README of the github page? :)

Awesome with the interest in multi-ligands. I'll clean up my code a bit and submit a pull-request when I feel it is ready
