### ISSUE TITLE
Questions about RDKit conformer generation, fast point cloud conformer fitting, and EquiBind-R meaning.

### ISSUE THREAD

**Issue by yufengwhy** [HannesStark/EquiBind#44]
|   | Code |Paper |
| ------------- | ------------- |------------- |
| Input  | PDBBind ground truth coord after rotation and translation |RDKit conformer  |
| kabsch_rmsd_loss  | SVD  | 3.2.2closed form solution  |

1.  why above mismatch in code and paper?
2. Where is the "3.2.2closed form solution" in the code? do this once or each epoch?
3. what is the difference between EQUIBIND-U and EQUIBIND-R?

**Comment by HannesStark** [comment]
1. EquiBind U indeed refers to running EquiBind without the point cloud fitting. You are correct that we do not apply any distance geometry regularization in EquiBind-R since it only performs rigid body transformations.
2. The ligand fitting only is performed once.
3. Yes, the ligand fitting is implemented here.
4. In equation 1 it can be observed that the term we are maximizing is independent of other torsion angles.
