### ISSUE TITLE
Conformations are being sampled even with use_rdkit_coords=False

### ISSUE THREAD

**Issue by jadolfbr** [HannesStark/EquiBind#61]
The output ligand is significantly changing conformation even with `use_rdkit_coords=False`

This seems strange and is behavior that we do not want for some use cases.  Is there anyway to force the input structure as the structure to bind?

**Comment by HannesStark** [comment]
Yes, this is what the rigid_redocking model does. There the ligand is treated as a rigid body and its conformation is not changed at all.
In the config file you can specify the path rigid_redocking instead of flexible_self_docking.

Please let me know if you need more information to resolve your issue or if you can already get it running with that!

**Comment by jadolfbr** [comment]
Thanks for the info!  This is very helpful!
