### ISSUE TITLE
About the Training Efficiency

### ISSUE THREAD

**Issue by youqingxiaozhua** [HannesStark/EquiBind#65]
Dear authors:

Thanks for your great work and public codes. I am trying to do some further research based on your work. However, I found the training process is really slow, with less than 20% GPU utilization. The val loss on PDBBind is still decreasing after **seven** days of training on one V100 GPU. Do you have any advice to improve the training efficiency? I found you leave a TODO comment to run SVD in batches. Do you have any updates on this? 

Many thanks!

**Comment by HannesStark** [comment]
Hi!

Unfortunately, we have not looked into running SVD in batches any further and have not implemented this. 
I would also recommend checking out the new DiffDock method instead of EquiBind since it provides significantly better accuracy. (However, it is even slower at training since it uses the rather heavy e3nns).
